# Generated by Django 3.2.9 on 2022-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('mobile_num', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('junior_dev', 'Junior Developer'), ('senior_dev', 'Senior Developer'), ('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('employee', 'Employee')], default='employee', help_text='Job position taken', max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('employee_id', models.CharField(max_length=10)),
            ],
        ),
    ]
