# Generated by Django 3.2.9 on 2022-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_num',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
