# Generated by Django 3.2.9 on 2022-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('junior_dev', 'Junior Developer'), ('senior_dev', 'Senior Developer'), ('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('employee', 'Employee')], default='employee', help_text='Job position taken', max_length=20),
        ),
    ]
